language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - PREFER="--prefer-lowest"
    - PREFER="--prefer-dist"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer update --no-interaction $PREFER

script:
  - composer test
